### ISSUE TITLE
Not working in node 4 because of `let`

### ISSUE THREAD

**Issue by MiniGod** [agirorn/jasmine-vow#2]
This module is not working in node 4.

I get the following error when calling `require('jasmine-vow')`:

`SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode`.

<details><summary>See stack trace</summary><p>

    /path/to/repo/node_modules/jasmine-vow/lib/wrap.js:9
        let cb = isFunction(description)
        ^^^
    
    SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
        at exports.runInThisContext (vm.js:53:16)
        at Module._compile (module.js:373:25)
        at Object.Module._extensions..js (module.js:416:10)
        at Module.load (module.js:343:32)
        at Function.Module._load (module.js:300:12)
        at Module.require (module.js:353:17)
        at require (internal/module.js:12:17)
        at Object.<anonymous> (/path/to/repo/node_modules/jasmine-vow/lib/vow.js:1:76)
        at Module._compile (module.js:409:26)
        at Object.Module._extensions..js (module.js:416:10)
</p></details>

**Comment by agirorn** [comment]
I know and it is stated in the [package.json](https://github.com/agirorn/jasmine-vow/blob/master/package.json#L47) that it only works for node 6.

Is this a must for you?
Can you not upgrade your project to use node 6 of 8?
